const fs = require('fs');
const path = require('path');

const W = 32;
const H = 16;
const BAYER = [[0, 8, 2, 10], [12, 4, 14, 6], [3, 11, 1, 9], [15, 7, 13, 5]];

function tri(t) {
  return 1 - Math.abs(2 * (t - Math.floor(t)) - 1);
}

function rnd(a, b) {
  let h = Math.imul(a + 1, 0x27d4eb2d) ^ Math.imul(b + 1, 0x165667b1);
  h = Math.imul(h ^ (h >>> 15), 0x85ebca6b);
  h = Math.imul(h ^ (h >>> 13), 0xc2b2ae35);
  return ((h ^ (h >>> 16)) >>> 0) / 4294967296;
}

function wrapDistance(x, y, cx, cy) {
  const dx = Math.min(Math.abs(x - cx), W - Math.abs(x - cx));
  const dy = Math.min(Math.abs(y - cy), H - Math.abs(y - cy));
  return Math.hypot(dx, dy);
}

const motifs = {
  rings(x, y) {
    return Math.floor(wrapDistance(x + 0.5, y + 0.5, 11, 8) / 2.2) % 3;
  },
  dither(x, y) {
    const v = 2 * (0.7 * tri(x / W) + 0.3 * tri(y / H));
    return Math.min(2, Math.floor(v + BAYER[y % 4][x % 4] / 16));
  },
  mosaic(x, y) {
    const block = rnd(x >> 2, y >> 2);
    const speck = rnd((x >> 1) + 99, (y >> 1) + 7);
    if (block > 0.72) return 2;
    if (block > 0.42) return speck > 0.8 ? 2 : 1;
    return speck > 0.9 ? 1 : 0;
  },
  plasma(x, y) {
    const v = Math.sin(2 * Math.PI * x / W)
      + Math.sin(2 * Math.PI * y / H)
      + Math.sin(2 * Math.PI * (x + 2 * y) / W);
    return Math.floor(((v + 3) / 6) * 7) % 3;
  },
  truchet(x, y) {
    const lx = (x & 7) + 0.5;
    const ly = (y & 7) + 0.5;
    const flip = rnd((x >> 3) + 5, (y >> 3) + 3) > 0.5;
    const a = flip ? Math.hypot(lx, ly) : Math.hypot(8 - lx, ly);
    const b = flip ? Math.hypot(8 - lx, 8 - ly) : Math.hypot(lx, 8 - ly);
    const edge = Math.min(Math.abs(a - 4), Math.abs(b - 4));
    if (edge < 1) return 2;
    return edge < 2 ? 1 : 0;
  },
};

function mask(fn, level) {
  let d = '';
  for (let y = 0; y < H; y++) {
    let x = 0;
    while (x < W) {
      if (fn(x, y) !== level) {
        x++;
        continue;
      }
      const start = x;
      while (x < W && fn(x, y) === level) x++;
      d += `M${start} ${y}h${x - start}v1h-${x - start}z`;
    }
  }
  const svg = `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 ${W} ${H}' shape-rendering='crispEdges'><path d='${d}'/></svg>`;
  return `url("data:image/svg+xml,${svg.replace(/</g, '%3C').replace(/>/g, '%3E')}")`;
}

const css = Object.entries(motifs).map(([name, fn]) => [
  `.motif-${name} .card__art::before { mask-image: ${mask(fn, 1)}; }`,
  `.motif-${name} .card__art::after { mask-image: ${mask(fn, 2)}; }`,
].join('\n')).join('\n\n');

const header = '/* Generated by tools/motifs.js. Edit that file and rerun it. */\n\n';

fs.writeFileSync(path.join(__dirname, '..', 'motifs.css'), header + css + '\n');
