window.PORTFOLIO = {
  hero: {
    id: "commander",
    name: "El Linzer",
    cost: ["U", "G"],
    type: "Legendary Creature — Human Engineer",
    rarity: "mythic",
    rules: [
      "Django and Kotlin, from internal admin tools to Android push alerts.",
      "Whenever a manual workflow enters the battlefield, automate it.",
    ],
    flavor: "Came to code from case management. Still solving for people.",
    pt: "4/5",
    links: [],
    section: "hero",
    pitch:
      "Software engineer in Chicago building Django backends, internal tooling, and the automation that takes busywork off people’s plates.",
    email: "elinzer5@gmail.com",
  },
  cards: [
    {
      id: "event-evader",
      name: "Event Evader",
      cost: ["R", "G"],
      type: "Artifact — Mobile App",
      rarity: "mythic",
      rules: [
        "Alerts you to concerts and games near you so you can route around the traffic.",
        "Live on Android and iOS.",
      ],
      flavor: "Co-founder & Engineer · 2023–present",
      links: [
        { label: "Site", href: "https://eventevader.com", primary: true },
        {
          label: "Android",
          href: "https://play.google.com/store/apps/details?id=com.eventevader.release",
        },
        {
          label: "iOS",
          href: "https://apps.apple.com/us/app/event-evader/id6752586846",
        },
      ],
      section: "projects",
    },

    {
      id: "admin-rbac",
      name: "Least Privilege",
      cost: ["W", "U"],
      type: "Enchantment — SpotHero",
      rarity: "mythic",
      rules: [
        "Replaced legacy is_staff fallbacks with explicit permission checks.",
        "Role-based access across SpotHero’s whole internal admin platform.",
      ],
      flavor: "No one passes without the right key.",
      // pt: "15+ groups",
      links: [],
      section: "achievements",
    },
    {
      id: "reseller-enforcement",
      name: "Reseller Enforcement",
      cost: ["B"],
      type: "Sorcery — SpotHero",
      rarity: "rare",
      rules: [
        "A new Django app that detects reseller fraud and acts on it.",
        "Opens Salesforce tickets and runs cancel-and-ban workflows on its own.",
      ],
      flavor: "Exile target scalper.",
      links: [],
      section: "achievements",
    },
    {
      id: "cancellation-consensus",
      name: "Cancellation Consensus",
      cost: ["U", "B"],
      type: "Enchantment — SpotHero",
      rarity: "rare",
      rules: [
        "Built automatic cancellation handling across four ticketing vendors.",
        "Stopped drivers from booking parking for cancelled shows.",
      ],
      flavor: "Four sources. One truth.",
      links: [],
      section: "achievements",
    },
    {
      id: "push-pipeline",
      name: "Push Pipeline",
      cost: ["R"],
      type: "Artifact — Event Evader",
      rarity: "rare",
      rules: [
        "Django notification service, token API, and Celery-scheduled delivery.",
        "Firebase Cloud Messaging and notification preferences on Android.",
      ],
      flavor: "Your venue just announced a show.",
      links: [],
      section: "achievements",
    },
    {
      id: "venue-api",
      name: "Venue Finder",
      cost: ["G"],
      type: "Instant — Event Evader",
      rarity: "uncommon",
      rules: [
        "REST endpoints for following, searching, and listing venues.",
        "Live event data from the Ticketmaster Discovery API.",
      ],
      links: [],
      section: "achievements",
    },

    {
      id: "saga-spothero",
      name: "SpotHero",
      cost: ["U", "W"],
      type: "Saga — SpotHero",
      rarity: "mythic",
      rules: [
        "Built apps for Customer Service, Sales, and Supply.",
        "Automated reseller fraud handling, end to end.",
        "Led role-based access control across the admin platform.",
      ],
      flavor: "Software Engineer · 2023–present",
      links: [
        { label: "Company", href: "https://spothero.com", primary: true },
      ],
      section: "experience",
    },
    {
      id: "saga-code-nation",
      name: "Code Nation",
      cost: ["W"],
      type: "Saga — Code Nation",
      rarity: "uncommon",
      rules: [
        "Taught HTML, CSS, and JavaScript to high school students.",
        "Mentored them through hands-on projects.",
      ],
      flavor: "Classroom Volunteer · 2023–2024",
      links: [{ label: "Org", href: "https://codenation.org", primary: true }],
      section: "experience",
    },
    {
      id: "saga-sarahs-circle",
      name: "Sarah’s Circle",
      cost: ["W", "G"],
      type: "Saga — Sarah’s Circle",
      rarity: "uncommon",
      rules: [
        "Managed a caseload of 25 clients with competing priorities.",
        "Coordinated across government, medical, and mental health systems.",
        "Reached an 84% rate of stable housing outcomes.",
      ],
      flavor: "Case Manager · 2020–2022",
      links: [
        { label: "Org", href: "https://www.sarahs-circle.org", primary: true },
      ],
      section: "experience",
    },

    {
      id: "land-linkedin",
      name: "LinkedIn",
      cost: [],
      identity: ["U"],
      type: "Land",
      rarity: "common",
      rules: ["Tap: add one professional connection."],
      links: [
        {
          label: "Open",
          href: "https://www.linkedin.com/in/elinzer/",
          primary: true,
        },
      ],
      section: "contact",
    },
    {
      id: "land-github",
      name: "GitHub",
      cost: [],
      identity: ["B"],
      type: "Land",
      rarity: "common",
      rules: ["Tap: reveal the top card of the commit history."],
      links: [
        { label: "Open", href: "https://github.com/elinzer", primary: true },
      ],
      section: "contact",
    },
    {
      id: "land-email",
      name: "Email",
      cost: [],
      identity: ["W"],
      type: "Land",
      rarity: "common",
      rules: ["Tap: begin a conversation."],
      links: [
        { label: "Open", href: "mailto:elinzer5@gmail.com", primary: true },
      ],
      section: "contact",
    },
  ],
};
